# Generated by Django 4.2 on 2023-04-19 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('Entity_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Entity_Name', models.CharField(max_length=500)),
                ('Entity_Description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Entities',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('Group_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Group_Name', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.entities')),
            ],
            options={
                'db_table': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=500)),
                ('Last_Name', models.CharField(max_length=500)),
                ('Role', models.CharField(max_length=500)),
                ('Date_Of_Joining', models.DateField()),
                ('Email_User', models.CharField(max_length=500)),
                ('Password_User', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyApp.groups')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
    ]
