# Generated by Django 4.2 on 2023-04-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='entities',
            name='deleted_by',
            field=models.IntegerField(default='NULL', null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='groups',
            name='deleted_by',
            field=models.IntegerField(default='NULL', null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='deleted_by',
            field=models.IntegerField(default='NULL', null=True),
        ),
    ]
