# Generated by Django 4.2 on 2023-04-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_alter_entities_deleted_by_alter_groups_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entities',
            name='Entity_Number',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Entity_Description',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Entity_Name',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='deleted_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groups',
            name='deleted_by',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_by',
            field=models.IntegerField(),
        ),
    ]
