# Generated by Django 4.2 on 2023-04-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_entities_entity_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='Email_User',
            new_name='User_Email',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Group',
            new_name='User_Group',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Password_User',
            new_name='User_Number',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='Role',
            new_name='User_Password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Date_Of_Joining',
        ),
        migrations.AddField(
            model_name='users',
            name='User_Role',
            field=models.CharField(default='NULL', max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Entity_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Entity_Name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='Entity_Number',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entities',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entities',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='deleted_by',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
