# Generated by Django 4.2 on 2023-04-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_rename_email_user_users_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='User_Group',
        ),
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
