# Generated by Django 4.2 on 2023-04-24 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_remove_users_user_group_delete_groups_delete_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entities',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='entities',
            name='deleted_by',
        ),
    ]
