# Generated by Django 4.1.7 on 2023-04-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('Entity_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Entity_Number', models.CharField(max_length=500)),
                ('Entity_Name', models.CharField(max_length=500)),
                ('Entity_Description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Entities',
            },
        ),
    ]
